CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL,
    name text,
    nonce text NOT NULL,
    password text NOT NULL,
    uuid uuid DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS classes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    user_id integer NOT NULL REFERENCES users(id),
    uuid uuid DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS students (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    user_id integer NOT NULL REFERENCES users(id),
    uuid uuid DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS seats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id integer NOT NULL REFERENCES classes(id),
    student_id integer NOT NULL REFERENCES students(id)
);
