CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    email text NOT NULL,
    name text,
    nonce text NOT NULL,
    password text NOT NULL,
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS sections (
    name text,
    user_id uuid NOT NULL REFERENCES users(id),
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS students (
    name text,
    user_id uuid NOT NULL REFERENCES users(id),
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4()
);

CREATE TABLE IF NOT EXISTS seats (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id uuid NOT NULL REFERENCES sections(id),
    student_id uuid NOT NULL REFERENCES students(id)
);
